name: Dependency Review

on:
  pull_request:

permissions: {}

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/dependency-review-action@38e98a85e00a1e4a7b9ede0e02e70b2f05a31cc4  # v4.6.0
        with:
          fail-on-severity: high
